### ISSUE TITLE
Issue with macOS Catalina?

### ISSUE THREAD

**Issue by stanifrolov** [AlexanderWillner/deepl-alfred-workflow2#8]
After upgrading to Catalina, I seem to have a problem using this workflow. I don't get any result if I type
**dl This is just an example**. 

But after a few seconds, I get the option to use Google Search for the whole query.

-----
macOS Catalina 10.15
Alfred 4.0.4
DeepL workflow v1.16

**Comment by AlexanderWillner** [comment]
Thanks, not yet on Catalina (waiting till the new Mail.app is not going to lose e-mails anymore). In the mean time, have you seen https://www.deepl.com/app?

**Comment by stanifrolov** [comment]
Thanks for the response!
Oh okay. Yes, I have and I'll give it a try.

**Comment by csteinlehner** [comment]
I have the same issue on Mojave (10.14.6). After I write the dot, I get just the option for a google query.

**Comment by glumb** [comment]
The _dlfr_ workflow worked. So I just modified it to `./deepl.sh -l "EN" "{query}"`

**Comment by romebot2** [comment]
not been able to make this work and it was suggested that I post here for some help. here's my post on the alfred forum. thanks for the help.[https://www.alfredforum.com/topic/14343-deepl-workflow-problems/?tab=comments#comment-73470]( https://www.alfredforum.com/topic/14343-deepl-workflow-problems/?tab=comments#comment-73470)

**Comment by AlexanderWillner** [comment]
Should be fixed, please [download](https://github.com/AlexanderWillner/deepl-alfred-workflow2/releases/latest/download/Deepl-Translate.alfredworkflow) and test.

**Comment by romebot2** [comment]
Thank you Alexander, but I'm still having issues. I deleted the whole thing and started over w/ your new workflow. I didn't touch any settings and tried an example. 

-In the first window that pops up when you install and it asks for a category to save it in, to the right it says target EN (also when you click the [x] in the upper right). Does this mean the language I'm writing in, or that language I'm translating to? To be sure I tried it as "EN", and also set it to "DE" but I still get the same translation to English, but w/o spaces like in the forum post screenshot (and I still sometimes get the two options when I start typing like in the forum screenshot--before a period is typed to complete the sentence).

I want to write in English and covert to German. Where do I change those settings--I'm assuming the code for German is DE, but maybe I'm wrong. I tried to change different variables, in the main window and the alt language, where it says "FR", but the answer is always in English.

And sometimes when I try 1-2 times, I get a too many requests error. I thought that more would be allowed. 

Thanks for the help!

below are a couple of attempts w/ DE and EN using the debugger:

```
[08:48:35.066] Deepl-Translate[Script Filter] Queuing argument 'this is a test.'
[08:48:36.286] Deepl-Translate[Script Filter] Script with argv '(null)' finished
[08:48:36.288] Deepl-Translate[Script Filter] {
  "items": [
    {
      "uid": null,
      "arg": "thisisatest",
      "valid": "yes",
      "autocomplete": "autocomplete",
      "title": "thisisatest"
    }
  ]
}
```

-----
```
[08:47:59.545] Logging Started...
[08:48:06.944] Deepl-Translate[Script Filter] Queuing argument 'this is a test.'
[08:48:07.704] Deepl-Translate[Script Filter] Script with argv '(null)' finished
[08:48:07.706] Deepl-Translate[Script Filter] {
  "items": [
    {
      "uid": null,
      "arg": "thisisatest",
      "valid": "yes",
      "autocomplete": "autocomplete",
      "title": "thisisatest"
    }
  ]
}
```

**Comment by AlexanderWillner** [comment]
Thanks a lot. As it has nothing to do with Catalina, I'm closing this one. 

Regarding the too many requests: see #5 (actually, currently blocking everything else).

Regarding source and destination language: created #9 - partly hard coded in this line: https://github.com/AlexanderWillner/deepl-alfred-workflow2/blob/551064655f87a511ef86f04887b7a58c13d58bea/deepl.sh#L63

**Comment by romebot2** [comment]
Thanks Alexander, but I think your answer is a bit over my head. :) What should I do? copy that code somewhere? (is it fixable?) best, R

**Comment by AlexanderWillner** [comment]
Sorry. In short: due to issue #5 I'd rather suggest to use the [official app](http://deepl.com/app) for now.
